---

- name: Swap off
  shell: swapoff -a
  when: swap_state.stdout != ''

- name: Configure /etc/fstab
  replace:
    path: /etc/fstab
    regexp: ([^\s]+\s+swap\s+.*)
    replace: '# \1'
  when: swap_state_in_fstab.stdout != '0'
