--- 

- name: Get swap state
  shell: swapon -v
  register: swap_state
  check_mode: false
  changed_when: false

- name: Get swap check for /etc/fstab
  shell: grep -v "\s*#" /etc/fstab | awk '{print $2}' | grep swap -c
  register: swap_state_in_fstab
  check_mode: false
  changed_when: false
  ignore_errors: true
